# Generated by Django 6.0.3 on 2026-04-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_review_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
